version: '3'
services:
  frontend:
    build:
      context: . # our frontend is in the root directory so ?
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    depends_on:
      - backend  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=${PRODUCTION_DB_USERNAME}
      - DB_PASSWORD=${PRODUCTION_DB_PASSWORD} # with our info
    depends_on:
      - mysql  

  mysql:
    image: mysql:8.0  
    ports:
      - "3306:3306" # not sure which port so double check
    environment:
      MYSQL_ROOT_PASSWORD: ${PRODUCTION_DB_PASSWORD} # with our info
      MYSQL_DATABASE: ${PRODUCTION_DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql  

volumes:
  db_data:  